version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache_custom
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ../Bibliodrive/:/var/www/html
      - ./apache2.conf:/etc/apache2/apache2.conf

  db:
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bibliodrive
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
